// Generated by CoffeeScript 1.8.0
define({
  layout: {
    regions: {
      left: 'left',
      right: 'right'
    }
  },
  views: [
    {
      name: 'inline:left',
      region: 'left',
      avoidLoadingHandlers: true
    }, {
      name: 'inline:right',
      region: 'right',
      avoidLoadingHandlers: true
    }
  ]
});
